% Function apply_step_two_neighbors.
function   [core_left, ...
            partition_left, ...
            basis_left, ...
            core_parent, ...
            partition_right, ...
            basis_right, ...
            core_right]...
        = ...
            apply_step_two_neighbors(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                core_left, ...
                partition_left, ...
                basis_left, ...
                core_parent, ...
                partition_right, ...
                basis_right, ...
                core_right ...
    )
% Apply (two-sided) step of triggering a block.
% Input requirement: both neighbors exist.

% Takes care of changing the format
% of i/o variables (packs/unpacks from cells before/after applying the
% function).

%
%-------------------------------------------------------------------%

% pack neighbors and bases into cells
Cores_left = {core_left};
Cores_right = {core_right};
Bases_left = {basis_left};
Bases_right = {basis_right};

% apply step
[Cores_left, ...
            partition_left, ...
            Bases_left, ...
            core_parent, ...
            partition_right, ...
            Bases_right, ...
            Cores_right]...
        = ...
            cell_apply_step(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                Cores_left, ...
                partition_left, ...
                Bases_left, ...
                core_parent, ...
                partition_right, ...
                Bases_right, ...
                Cores_right, ...
                true, ... apply_update_to_left_side_indicator
                true, ... apply_update_to_right_side_indicator
                false, ... full_rank_tall_validation_indicator
                false ... full_rank_wide_validation_indicator
    );
% unpack neighbors and bases from cells
core_left = Cores_left{1};
core_right = Cores_right{1};
basis_left = Bases_left{1};
basis_right = Bases_right{1};
end