% Function apply_step_only_left_neighbors.
function   [core_left, ...
            partition_left, ...
            basis_left, ...
            core_parent, ...
            partition_right, ...
            basis_right]...
        = ...
            apply_step_only_left_neighbors(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                core_left, ...
                partition_left, ...
                basis_left, ...
                core_parent, ...
                partition_right, ...
                basis_right ...
    )
% Apply (two-sided) step of triggering a block that has only left neighbors.
% Input requirement: parent mapping has a left neighbor.

% Essentially does the same as function apply_step_two_neighbors but has
% less i/o variables (the redundant - i.e. core of left neighbor - has been removed).
% Read documentation of function apply_step_two_neighbors for more info.

%-------------------------------------------------------------------%

% pack neighbors and bases into cells
Cores_left = {core_left};
Cores_right = {}; % no right neighbor
Bases_left = {basis_left};
Bases_right = {basis_right};

% apply step
[Cores_left, ...
            partition_left, ...
            Bases_left, ...
            core_parent, ...
            partition_right, ...
            Bases_right, ...
            Cores_right]...
        = ...
            cell_apply_step(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                Cores_left, ...
                partition_left, ...
                Bases_left, ...
                core_parent, ...
                partition_right, ...
                Bases_right, ...
                Cores_right, ...
                true, ... apply_update_to_left_side_indicator
                true, ... apply_update_to_right_side_indicator
                false, ... full_rank_tall_validation_indicator
                false ... full_rank_wide_validation_indicator
    );
% unpack neighbors and bases from cells
core_left = Cores_left{1};
% [no action] no right neighbor
basis_left = Bases_left{1};
basis_right = Bases_right{1};
end