% Function apply_step_only_right_neighbors.
function   [partition_left, ...
            basis_left, ...
            core_parent, ...
            partition_right, ...
            basis_right, ...
            core_right]...
        = ...
            apply_step_only_right_neighbors(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                partition_left, ...
                basis_left, ...
                core_parent, ...
                partition_right, ...
                basis_right, ...
                core_right ...
    )
% Apply (two-sided) step of triggering a block that has only right neighbors.
% Input requirement: parent mapping has a right neighbor.

% Essentially does the same as function apply_step_two_neighbors but has
% less i/o variables (the redundant - i.e. core of right neighbor - has been removed).
% Read documentation of function apply_step_two_neighbors for more info.

%-------------------------------------------------------------------%

% pack neighbors and bases into cells
Cores_left = {}; % no left neighbors
Cores_right = {core_right};
Bases_left = {basis_left};
Bases_right = {basis_right};

% apply step
[Cores_left, ...
            partition_left, ...
            Bases_left, ...
            core_parent, ...
            partition_right, ...
            Bases_right, ...
            Cores_right]...
        = ...
            cell_apply_step(...
                i, ...      % triggered block block-coordinates: row
                j, ...      % triggered block block-coordinates: column
                tol_numrank, ...
                Cores_left, ...
                partition_left, ...
                Bases_left, ...
                core_parent, ...
                partition_right, ...
                Bases_right, ...
                Cores_right, ...
                true, ... apply_update_to_left_side_indicator
                true, ... apply_update_to_right_side_indicator
                false, ... full_rank_tall_validation_indicator
                false ... full_rank_wide_validation_indicator
    );
% unpack neighbors and bases from cells
% [no action] no left neighbors
core_right = Cores_right{1};
basis_left = Bases_left{1};
basis_right = Bases_right{1};
end